### ISSUE TITLE
Subissue: Integrate HashiCorp Vault for Secrets Management

### ISSUE THREAD

**Issue by jojomo96** [flomero/ft_transcendence#22]
## Objective
This list focuses on setting up HashiCorp Vault in a secure and functional state for use in the **Transcendence** project. Further integration with the application and secret management tasks will follow after the setup.

---

### 1. **Deploy Vault Using Docker**
   - [x] **Create a Docker Compose File**:  
     - Define a `docker-compose.yml` file for Vault with a backend (e.g., file or database storage).  
     - Example minimal configuration:
       ```yaml
       version: '3.8'
       services:
         vault:
           image: hashicorp/vault:latest
           container_name: vault
           ports:
             - "8200:8200"
           environment:
             VAULT_DEV_ROOT_TOKEN_ID: "root" # Change this for production
             VAULT_LOCAL_CONFIG: |
               {
                 "backend": {
                   "file": {
                     "path": "/vault/data"
                   }
                 },
                 "listener": {
                   "tcp": {
                     "address": "0.0.0.0:8200",
                     "tls_disable": 1
                   }
                 },
                 "default_lease_ttl": "168h",
                 "max_lease_ttl": "720h"
               }
           volumes:
             - ./vault/data:/vault/data
       ```

   - [x] **Run Vault**:  
     - Start Vault using `docker-compose up -d`.  
     - Verify the container is running with `docker ps`.

### 2. **Initialize Vault**
   - [x] **Access the Vault Container**:  
     - Run `docker exec -it vault sh` to access the container’s shell.

   - [x] **Initialize Vault**:  
     - Execute `vault operator init` to initialize the Vault instance.  
     - Copy and securely store the unseal keys and initial root token.

   - [x] **Unseal Vault**:  
     - Use `vault operator unseal` with at least 3 of the unseal keys to make Vault operational.

### 3. **Configure Backend Storage (Optional for Non-Dev Mode)**
   - [x] **Choose a Backend**:  
     - For production, select a robust storage backend like AWS S3, Consul, or a database.

   - [x] **Update Configuration**:  
     - Edit the `docker-compose.yml` file to reflect the chosen backend.

   - [x] **Restart Vault**:  
     - Restart the Vault service with `docker-compose down` and `docker-compose up -d`.

### 4. **Enable Authentication Backend**
   - [ ] **Enable Token Auth** (default for setup):  
     - Run `vault auth enable token`.  
     - Generate a new token for testing: `vault token create`.

### 5. **Verify Vault Setup**
   - [ ] **Access Vault UI**:  
     - Open `http://localhost:8200` in your browser.  
     - Log in using the root token from initialization.

   - [ ] **Test Secrets Engine**:  
     - Enable Key/Value secrets: `vault secrets enable -path=kv kv`.  
     - Store a test secret: `vault kv put kv/test key=value`.  
     - Retrieve the secret: `vault kv get kv/test`.

---

## Next Steps
Once the setup is complete, you can proceed with:
- Configuring authentication methods (e.g., AppRole, LDAP).
- Setting up secrets storage and rotation.
- Integrating Vault into the application.
